### ISSUE TITLE
Documentation Error Helm Provider

### ISSUE THREAD

**Issue by ark-lucid** [hashicorp/terraform-provider-helm#1686]
### Terraform, Provider, Kubernetes and Helm Versions
Terraform v1.5.7

```
Terraform version: 1.67
Provider version: 3.0.2
Kubernetes version: N/A
```

### Affected Resource(s)

- helm_release
- helm_repository

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release

<img width="617" height="658" alt="Image" src="https://github.com/user-attachments/assets/4a6db6c8-eece-4215-a591-a48e13a7786c" />

This documentation seems ti be wrong as we cannot use "set" 2 times.

**Comment by jaylonmcshan19-x** [comment]
Resolved here: https://github.com/hashicorp/terraform-provider-helm/pull/1676

**Comment by hsiam261** [comment]
@jaylonmcshan19-x How is this resolved?
The doc still shows this:

<img width="1064" height="1041" alt="Image" src="https://github.com/user-attachments/assets/bf8c7d01-b382-47a8-9e49-e64f01a0e8b3" />

The doc can be found [here](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#example-usage---chart-repository).

Please update the docs in the docs website. Otherwise it will just confuse users and waste their time.
