### ISSUE TITLE
Template render failure with provider but not with plain helm - after 1.3.2 -> 2.0.x

### ISSUE THREAD

**Issue by chrisbulgaria** [hashicorp/terraform-provider-helm#665]
Not sure exactly what is going on here - but below very simplistic chart (values.yaml, secret.yaml) renders fine with plain helm (as well with the exact version used by the provider) , but not with the provider.
It looks like the "custom: {} "  empty list in the values file is translated somewhere to nil . 
With provider version 1.3.2 all is fine. 

This was detected (and now reproduced independently of that specific chart) here: 
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1998

```
Terraform version: 14.3
Provider version: 2.0.2

```

### Affected Resource(s)
- helm_release

### Terraform Configuration Files
```hcl

resource "helm_release" "test" {
  name              = "test"
  chart             = "./test"
}
provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
  debug = true
}
```
################   chart files:
**values.yaml:**

`custom: {}`

**secret.yaml**

```
kind: Secret
apiVersion: v1
metadata:
  name: test
type: Opaque
data:
  {{- $values := merge dict .Values }}
  {{- $_ := set $values "custom" (merge dict $values.custom .Values) }}
```

### Debug Output
Error: template: test/templates/secret.yaml:8:52: executing "test/templates/secret.yaml" at <$values.custom>: wrong type for value; expected map[string]interface {}; got interface {}

### steps to reproduce
1. `terraform apply`

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mike-serchenia** [comment]
same story but just with a different type
 
```bash
Error: template: opentelemetry-collector/templates/daemonset.yaml:16:28: executing "opentelemetry-
collector/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap-agent.yaml") .>: error calling 
include: template: opentelemetry-collector/templates/configmap-agent.yaml:10:8: executing "opentelemetry-
collector/templates/configmap-agent.yaml" at <include "opentelemetry-collector.agentCollectorConfig" .>: error calling 
include: template: opentelemetry-collector/templates/_config.tpl:33:37: executing "opentelemetry-
collector.agentCollectorConfig" at <mustMergeOverwrite (deepCopy .)>: error calling mustMergeOverwrite: cannot append 
two different types (map, map)

```

**Comment by md2k** [comment]
Same problem with `.Capabilities.APIVersions.Has`, plain `helm install/upgrade` is ok, `helm template` fails with any conditions like : `{{- if .Capabilities.APIVersions.Has "mongodb.com/v1" }}` used in templates.
So new provider sounds like also use `helm template` and all our charts with such capabilities checks fails now.

Did new ticket for that : GH-685

**Comment by chrisbulgaria** [comment]
Probably that issue is different from the original - in the original helm template succeeds , only provider fails . It’s very specific to the handling of empty lists in the values file - there was some code change from 1.3 to 2.0 in merging the values .

**Comment by akirn** [comment]
> same story but just with a different type
> 
> ```shell
> Error: template: opentelemetry-collector/templates/daemonset.yaml:16:28: executing "opentelemetry-
> collector/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap-agent.yaml") .>: error calling 
> include: template: opentelemetry-collector/templates/configmap-agent.yaml:10:8: executing "opentelemetry-
> collector/templates/configmap-agent.yaml" at <include "opentelemetry-collector.agentCollectorConfig" .>: error calling 
> include: template: opentelemetry-collector/templates/_config.tpl:33:37: executing "opentelemetry-
> collector.agentCollectorConfig" at <mustMergeOverwrite (deepCopy .)>: error calling mustMergeOverwrite: cannot append 
> two different types (map, map)
> ```

I just encountered the exact same issue.

@mike-serchenia Have you found a fix or a workaround?

**Comment by mike-serchenia** [comment]
@akirn no, I've rollback to 1.13

**Comment by scoof** [comment]
I'm quite sure this is related to deep-merging dicts with falsy values - I have a helm chart where I do the merging in the chart itself, and that works on command line, and v 1.13 of the provider, but not v2.0.3
This would match the above in that it tries to merge the custom: {}, which evaluates to false, and then isn't merged. Maybe related issues: 
https://github.com/Masterminds/sprig/issues/134
https://github.com/helm/helm/issues/5238
https://github.com/imdario/mergo/issues/91

**Comment by scoof** [comment]
My issue is fixed at the latest main, so maybe importing the latest helm vendor code has fixed it...

**Comment by scoof** [comment]
confirmed, f20e7b043cf621cae5cacd26a1066fea3347d7f7 doesn't work, 30fb5af8b0efad59fc0b48a73142fc92aa6b8f4f works. @chrisbulgaria can you confirm the same?

**Comment by chrisbulgaria** [comment]
that sounds right .. cant easily test with an unreleased version (2.0.3 indeed still fails for me), will try to to it (or latest with the next minor release)

**Comment by chrisbulgaria** [comment]
Indeed this (the orginal issue here) is fixed for me in the provider version 2.1.0

**Comment by chrisbulgaria** [comment]
Closing as it appears fixed with 2.10
